const OPEN_MODAL = 'OPEN_MODAL'
const CLOSE_MODAL = 'CLOSE_MODAL'

const GET_PEOPLE = 'GET_PEOPLE'
const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCESS'
const GET_PEOPLE_ERROR = 'GET_PEOPLE_ERROR'

export default {
  OPEN_MODAL,
  CLOSE_MODAL,
  GET_PEOPLE,
  GET_PEOPLE_SUCCESS,
  GET_PEOPLE_ERROR
}
